export const TOURS_ACTION_TYPE = {
  FETCH_TOURS_SUCCESS: "FETCH_TOURS_SUCCESS",
  SET_CURRENT_CARD_DETAILS_INDEX: "SET_CURRENT_CARD_DETAILS_INDEX",
  REMOVE_CURRENT_CARD_IDNEX: "REMOVE_CURRENT_CARD_IDNEX",
};
