export const USER_ACTION_TYPE = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  REMOVE_CURRENT_USER: "REMOVE_CURRENT_USER",
  UPDATE_CURRENT_USER_PHOTO: "UPDATE_CURRENT_USER_PHOTO",
  UPDATE_CURRENT_SUER_TOKEN: "UPDATE_CURRENT_SUER_TOKEN",
};
